{application,goth,
             [{config_mtime,1738527008},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,jose,jason,finch]},
              {description,"A simple library to generate and retrieve Oauth2 tokens for use with Google Cloud Service accounts.\n"},
              {modules,['Elixir.Goth','Elixir.Goth.Application',
                        'Elixir.Goth.Client','Elixir.Goth.Config',
                        'Elixir.Goth.HTTPClient','Elixir.Goth.Token',
                        'Elixir.Goth.TokenStore']},
              {registered,[]},
              {vsn,"1.4.5"},
              {mod,{'Elixir.Goth.Application',[]}}]}.
