{application,plug_crypto,
             [{config_mtime,1771377826},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,crypto]},
              {description,"Crypto-related functionality for the web"},
              {modules,['Elixir.Plug.Crypto','Elixir.Plug.Crypto.Application',
                        'Elixir.Plug.Crypto.KeyGenerator',
                        'Elixir.Plug.Crypto.MessageEncryptor',
                        'Elixir.Plug.Crypto.MessageVerifier']},
              {registered,[]},
              {vsn,"2.0.0"},
              {mod,{'Elixir.Plug.Crypto.Application',[]}}]}.
